trigger:
  branches:
    include:
      - adf_publish

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - task: AzureCLI@2
    displayName: Deploy ARM Template to TEST
    inputs:
      azureSubscription: 'AzureServiceConnection'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group create \
          --resource-group rg-data-test \
          --template-file adf-dev-omg/ARMTemplateForFactory.json \
          --parameters adf-dev-omg/ARMTemplateParametersForFactory.json \
          --parameters factoryName=adf-test-omg
